### PR TITLE
feat: Xmas 2024 from xmas 2023

### PR DESCRIPTION
**Pull request by louis1706**

### CODE REVIEW

**Comment by louis1706** [comment]
[ERROR] [Exiled.Events] Patching failed! There are 3 broken patches.

**Review by VALERA771 — APPROVED** [review]
If everyting is working fine

**Comment by louis1706** [comment]
> If everyting is working fine

It's compile correctly i only got a nre but idk if it's was from this pr about Flammingo Spawning other than that it's all looks good

**Comment by louis1706** [comment]
Everything has been tested

**Review by IRacle1 — APPROVED** [review]

**Pull request merged**
