### PR TITLE
`Item::<T>Get()` and `Pickup::<T>Get()`

### PR DESCRIPTION
**Pull request by louis1706**

### CODE REVIEW

**Review by Jesus-QC — APPROVED** [review]

**Comment by ITeMbI4** [comment]
It will break all traspillers @louis1706 @Jesus-QC

**Comment by ITeMbI4** [comment]
```[2024-08-01 19:40:43.299 +00:00] [ERROR] [Exiled.Events] Patching by attributes failed!
                                 HarmonyLib.HarmonyException: Patching exception in method static InventorySystem.Items.Pickups.ItemPickupBase InventorySystem.InventoryExtensions::ServerCreatePickup(InventorySystem.Items.ItemBase item, InventorySystem.Items.Pickups.PickupSyncInfo psi, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, System.Boolean spawn, System.Action`1<InventorySystem.Items.Pickups.ItemPickupBase> setupMethod) ---> System.Reflection.AmbiguousMatchException: Ambiguous match found.
                                   at System.DefaultBinder.SelectMethod (System.Reflection.BindingFlags bindingAttr, System.Reflection.MethodBase[] match, System.Type[] types, System.Reflection.ParameterModifier[] modifiers) [0x001cc] in <05089c1b6989455fb1452c627044bac4>:0 
                                   at System.RuntimeType.GetMethodImplCommon (System.String name, System.Int32 genericParameterCount, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Reflection.CallingConventions callConv, System.Type[] types, System.Reflection.ParameterModifier[] modifiers) [0x00099] in <05089c1b6989455fb1452c627044bac4>:0 
                                   at System.RuntimeType.GetMethodImpl (System.String name, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Reflection.CallingConventions callConv, System.Type[] types, System.Reflection.ParameterModifier[] modifiers) [0x00000] in <05089c1b6989455fb1452c627044bac4>:0 
                                   at System.Type.GetMethod (System.String name, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Reflection.CallingConventions callConvention, System.Type[] types, System.Reflection.ParameterModifier[] modifiers) [0x00043] in <05089c1b6989455fb1452c627044bac4>:0 
                                   at System.Type.GetMethod (System.String name, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Type[] types, System.Reflection.ParameterModifier[] modifiers) [0x00000] in <05089c1b6989455fb1452c627044bac4>:0 
                                   at HarmonyLib.AccessTools+<>c__DisplayClass27_0.<Method>b__1 (System.Type t) [0x00000] in <0020ee40255b4dc7a0eb8b2a76225b38>:0 
                                   at HarmonyLib.AccessTools.FindIncludingBaseTypes[T] (System.Type type, System.Func`2[T,TResult] func) [0x00000] in <0020ee40255b4dc7a0eb8b2a76225b38>:0 
                                   at HarmonyLib.AccessTools.Method (System.Type type, System.String name, System.Type[] parameters, System.Type[] generics) [0x00091] in <0020ee40255b4dc7a0eb8b2a76225b38>:0 
                                   at Exiled.Events.Patches.Generic.PickupControlPatch+<Transpiler>d__0.MoveNext () [0x00069] in C:\Users\kosha\OneDrive\Cauterizers\EXILED Cauterizers\EXILED\Exiled.Events\Patches\Generic\PickupControlPatch.cs:47 
                                   at System.Collections.Generic.List`1[T].AddEnumerable (System.Collections.Generic.IEnumerable`1[T] enumerable) [0x00059] in <05089c1b6989455fb1452c627044bac4>:0 
                                   at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x00062] in <05089c1b6989455fb1452c627044bac4>:0 
                                   at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00018] in <a3536978e9984063a5ca6c790db4d471>:0 
                                   at HarmonyLib.CodeTranspiler.GetResult (System.Reflection.Emit.ILGenerator generator, System.Reflection.MethodBase method) [0x00051] in <0020ee40255b4dc7a0eb8b2a76225b38>:0 
                                   at HarmonyLib.MethodBodyReader.FinalizeILCodes (HarmonyLib.Emitter emitter, System.Collections.Generic.List`1[T] transpilers, System.Collections.Generic.List`1[T] endLabels, System.Boolean& hasReturnCode) [0x0014a] in <0020ee40255b4dc7a0eb8b2a76225b38>:0 
                                   at HarmonyLib.MethodCopier.Finalize (HarmonyLib.Emitter emitter, System.Collections.Generic.List`1[T] endLabels, System.Boolean& hasReturnCode) [0x00000] in <0020ee40255b4dc7a0eb8b2a76225b38>:0 
                                   at HarmonyLib.MethodPatcher.CreateReplacement (System.Collections.Generic.Dictionary`2[System.Int32,HarmonyLib.CodeInstruction]& finalInstructions) [0x002be] in <0020ee40255b4dc7a0eb8b2a76225b38>:0 
                                   at HarmonyLib.PatchFunctions.UpdateWrapper (System.Reflection.MethodBase original, HarmonyLib.PatchInfo patchInfo) [0x00057] in <0020ee40255b4dc7a0eb8b2a76225b38>:0 
                                   at HarmonyLib.PatchClassProcessor.ProcessPatchJob (HarmonyLib.PatchJobs`1+Job[T] job) [0x000bb] in <0020ee40255b4dc7a0eb8b2a76225b38>:0 
                                    --- End of inner exception stack trace ---
                                   at HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) [0x0010f] in <0020ee40255b4dc7a0eb8b2a76225b38>:0 
                                   at HarmonyLib.PatchClassProcessor.Patch () [0x00093] in <0020ee40255b4dc7a0eb8b2a76225b38>:0 
                                   at Exiled.Events.Features.Patcher.PatchAll (System.Boolean includeEvents, System.Int32& failedPatch) [0x00060] in C:\Users\kosha\OneDrive\Cauterizers\EXILED Cauterizers\EXILED\Exiled.Events\Features\Patcher.cs:101```

Because there are used this
![image](https://github.com/user-attachments/assets/56d8f478-29f5-429d-918c-bc8841c12b2d)

**Comment by louis1706** [comment]
> Because there are used this image
> 
> ```
>                                  HarmonyLib.HarmonyException: Patching exception in method static InventorySystem.Items.Pickups.ItemPickupBase InventorySystem.InventoryExtensions::ServerCreatePickup(InventorySystem.Items.ItemBase item, InventorySystem.Items.Pickups.PickupSyncInfo psi, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, System.Boolean spawn, System.Action`1<InventorySystem.Items.Pickups.ItemPickupBase> setupMethod) ---> System.Reflection.AmbiguousMatchException: Ambiguous match found.
>                                    at System.DefaultBinder.SelectMethod (System.Reflection.BindingFlags bindingAttr, System.Reflection.MethodBase[] match, System.Type[] types, System.Reflection.ParameterModifier[] modifiers) [0x001cc] in <05089c1b6989455fb1452c627044bac4>:0 
>                                    at System.RuntimeType.GetMethodImplCommon (System.String name, System.Int32 genericParameterCount, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Reflection.CallingConventions callConv, System.Type[] types, System.Reflection.ParameterModifier[] modifiers) [0x00099] in <05089c1b6989455fb1452c627044bac4>:0 
>                                    at System.RuntimeType.GetMethodImpl (System.String name, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Reflection.CallingConventions callConv, System.Type[] types, System.Reflection.ParameterModifier[] modifiers) [0x00000] in <05089c1b6989455fb1452c627044bac4>:0 
>                                    at System.Type.GetMethod (System.String name, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Reflection.CallingConventions callConvention, System.Type[] types, System.Reflection.ParameterModifier[] modifiers) [0x00043] in <05089c1b6989455fb1452c627044bac4>:0 
>                                    at System.Type.GetMethod (System.String name, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Type[] types, System.Reflection.ParameterModifier[] modifiers) [0x00000] in <05089c1b6989455fb1452c627044bac4>:0 
>                                    at HarmonyLib.AccessTools+<>c__DisplayClass27_0.<Method>b__1 (System.Type t) [0x00000] in <0020ee40255b4dc7a0eb8b2a76225b38>:0 
>                                    at HarmonyLib.AccessTools.FindIncludingBaseTypes[T] (System.Type type, System.Func`2[T,TResult] func) [0x00000] in <0020ee40255b4dc7a0eb8b2a76225b38>:0 
>                                    at HarmonyLib.AccessTools.Method (System.Type type, System.String name, System.Type[] parameters, System.Type[] generics) [0x00091] in <0020ee40255b4dc7a0eb8b2a76225b38>:0 
>                                    at Exiled.Events.Patches.Generic.PickupControlPatch+<Transpiler>d__0.MoveNext () [0x00069] in C:\Users\kosha\OneDrive\Cauterizers\EXILED Cauterizers\EXILED\Exiled.Events\Patches\Generic\PickupControlPatch.cs:47 
>                                    at System.Collections.Generic.List`1[T].AddEnumerable (System.Collections.Generic.IEnumerable`1[T] enumerable) [0x00059] in <05089c1b6989455fb1452c627044bac4>:0 
>                                    at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x00062] in <05089c1b6989455fb1452c627044bac4>:0 
>                                    at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00018] in <a3536978e9984063a5ca6c790db4d471>:0 
>                                    at HarmonyLib.CodeTranspiler.GetResult (System.Reflection.Emit.ILGenerator generator, System.Reflection.MethodBase method) [0x00051] in <0020ee40255b4dc7a0eb8b2a76225b38>:0 
>                                    at HarmonyLib.MethodBodyReader.FinalizeILCodes (HarmonyLib.Emitter emitter, System.Collections.Generic.List`1[T] transpilers, System.Collections.Generic.List`1[T] endLabels, System.Boolean& hasReturnCode) [0x0014a] in <0020ee40255b4dc7a0eb8b2a76225b38>:0 
>                                    at HarmonyLib.MethodCopier.Finalize (HarmonyLib.Emitter emitter, System.Collections.Generic.List`1[T] endLabels, System.Boolean& hasReturnCode) [0x00000] in <0020ee40255b4dc7a0eb8b2a76225b38>:0 
>                                    at HarmonyLib.MethodPatcher.CreateReplacement (System.Collections.Generic.Dictionary`2[System.Int32,HarmonyLib.CodeInstruction]& finalInstructions) [0x002be] in <0020ee40255b4dc7a0eb8b2a76225b38>:0 
>                                    at HarmonyLib.PatchFunctions.UpdateWrapper (System.Reflection.MethodBase original, HarmonyLib.PatchInfo patchInfo) [0x00057] in <0020ee40255b4dc7a0eb8b2a76225b38>:0 
>                                    at HarmonyLib.PatchClassProcessor.ProcessPatchJob (HarmonyLib.PatchJobs`1+Job[T] job) [0x000bb] in <0020ee40255b4dc7a0eb8b2a76225b38>:0 
>                                     --- End of inner exception stack trace ---
>                                    at HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) [0x0010f] in <0020ee40255b4dc7a0eb8b2a76225b38>:0 
>                                    at HarmonyLib.PatchClassProcessor.Patch () [0x00093] in <0020ee40255b4dc7a0eb8b2a76225b38>:0 
>                                    at Exiled.Events.Features.Patcher.PatchAll (System.Boolean includeEvents, System.Int32& failedPatch) [0x00060] in C:\Users\kosha\OneDrive\Cauterizers\EXILED Cauterizers\EXILED\Exiled.Events\Features\Patcher.cs:101
> ```

yeap i am not suprised of the break i have expecting it ^^ still thanks for saying it

**Review by Vladislav-CS — APPROVED** [review]
It can potentially break transpilers in plugins that use Item.Get and Pickup.Get, but okay

**Comment by louis1706** [comment]
I will wait for third confirmation to know if i merge this or not

**Review by VALERA771 — APPROVED** [review]

**Comment by VALERA771** [comment]
I think transpilers won't be broken

**Pull request merged**
