### PR TITLE
Trello is no more & more NW Fix & Fix IL Code on dev

### PR DESCRIPTION
**Pull request by louis1706**
## Description
**Describe the changes** 
Fix NW Bug Again
 - https://git.scpslgame.com/northwood-qa/scpsl-bug-reporting/-/issues/377
 - https://git.scpslgame.com/northwood-qa/scpsl-bug-reporting/-/issues/52
 - https://git.scpslgame.com/northwood-qa/scpsl-bug-reporting/-/issues/198
 - https://git.scpslgame.com/northwood-qa/scpsl-bug-reporting/-/issues/119
Fix new NW Bug
 - https://git.scpslgame.com/northwood-qa/scpsl-bug-reporting/-/issues/367
 - https://git.scpslgame.com/northwood-qa/scpsl-bug-reporting/-/issues/55
 - https://git.scpslgame.com/northwood-qa/scpsl-bug-reporting/-/issues/378
 - https://git.scpslgame.com/northwood-qa/scpsl-bug-reporting/-/issues/316
 Removed Bug that have been fixed
 - https://trello.com/c/V0uHP2eV/5745-overwatch-overwatch-can-get-respawned-by-scp-049
Add Exiled fix for EscapingEvent and Reporting 

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?** (if this is a feature change)

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

**Other information**:

<br />

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentations
<br />

## Submission checklist

- [ ] I have checked the project can be compiled
- [ ] I have tested my changes and it worked as expected

### Patches (if there are any changes related to Harmony patches)
- [ ] I have checked no IL patching errors in the console

### Other
- [x] Still requires more testing

### CODE REVIEW

**Comment by louis1706** [comment]
Contain IL Code Error than need fix (i don't have time to finish them)

**Comment by VALERA771** [comment]
IL fixed?

**Comment by louis1706** [comment]
> IL fixed?

yes also fix one from DevBranch

**Comment by Misaka-ZeroTwo** [comment]
fix build errors

**Review by VALERA771 — APPROVED** [review]
Just need to fix build errors. Everything else is fine

**Comment by louis1706** [comment]
> fix build errors

Done

**Pull request merged**
