### PR TITLE
feat(ActivatingEventArgs): KnobStatus

### PR DESCRIPTION
**Pull request by LumiFae**
## Description
Adds the knob status indicator to ActivatingEventArgs

**What is the current behavior?** (You can also link to an open issue here)
You have to grab the KnobStatus from Scp914.KnobStatus

**What is the new behavior?** (if this is a feature change)
Adds ActivatingEventArgs.KnobSetting

<br />

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentations
<br />

## Submission checklist

- [x] I have checked the project can be compiled
- [x] I have tested my changes and it worked as expected

### Patches (if there are any changes related to Harmony patches)
- [ ] I have checked no IL patching errors in the console

### Other
- [ ] Still requires more testing

### CODE REVIEW

**Comment by VALERA771** [comment]
Can you add setting this value in patch?

**Comment by JayXTQ** [comment]
I have no clue how to, I tried to add it based on the code for the other events but it didn't work sadly, I can try looking further though.

**Comment by JayXTQ** [comment]
@VALERA771 after looking through the patches and me not knowing a single thing about IL and Transpilers, I gave up. But nameless told me there was an issue with the setter so I have fixed that, please review.

**Comment by VALERA771** [comment]
You sure that this value won't be override by event?

**Comment by JayXTQ** [comment]
What do you mean exactly?

**Review by iamalexrouse — APPROVED** [review]

**Comment by LumiFae** [comment]
@louis1706 the original title was correct and fits with the standards as I've been using them for the last 2 years, no need to edit it.

**Review by Misfiy — APPROVED** [review]

**Review by VALERA771 — APPROVED** [review]

**Pull request merged**
