### PR TITLE
feat: timed waves

### PR DESCRIPTION
**Pull request by JayXTQ**
## Description
Add easier and more readable to understand methods when controlling timed waves.

**What is the current behavior?** (You can also link to an open issue here)
There is no documentation behind these and sometimes the variables are a bit confusing on what they do.

**What is the new behavior?** (if this is a feature change)
There is now documentation, better use of the C# spec and better variable names.

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
Yes, it does make a breaking change but no one is required to change their code to use this.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentations
<br />

## Submission checklist

- [x] I have checked the project can be compiled
- [ ] I have tested my changes and it worked as expected

### Patches (if there are any changes related to Harmony patches)
- [ ] I have checked no IL patching errors in the console

### Other
- [x] Still requires more testing

### CODE REVIEW

**Comment by JayXTQ** [comment]
Just expanding on this PR, most of the stuff implemented here I have tested myself to see if it works just using the direct methods and it does.

**Review by VALERA771 — APPROVED** [review]
NW surprises me more and more

**Review by Misfiy — CHANGES_REQUESTED** [review]
Requested changes in DMs

**Review by Misfiy — APPROVED** [review]

**Comment by JayXTQ** [comment]
merge time!!!

**Comment by VALERA771** [comment]
Why github still displays you as a first-time contributor

**Pull request merged**
