### PR TITLE
`[Brealing changes]` Adding support of CanOpen

### PR DESCRIPTION
**Pull request by VALERA771**
## Description
**Describe the changes** 
Replacing `IsAllowed` with `CanOpen` and separate their logic.
- IsAllowed: can player interact (if false nothing will happen) (at first always true)
- CanOpen: can player open it  (if false door/locker will indicate that access is denied) (at first may be false or true)

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?** (if this is a feature change)

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
Replacing `IsAllowed` with `CanOpen` and separate their logic. Users need to replace IsAllowed with CanOpen if they used IsAllowed to deny access

**Other information**:

<br />

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentations
<br />

## Submission checklist

- [x] I have checked the project can be compiled
- [x] I have tested my changes and it worked as expected

### Patches (if there are any changes related to Harmony patches)
- [x] I have checked no IL patching errors in the console

### Other
- [ ] Still requires more testing

### CODE REVIEW

**Comment by louis1706** [comment]
Heavy breaking changes

**Comment by VALERA771** [comment]
I can't imagine better name for it. IsAllowed represents CanInteract

**Comment by louis1706** [comment]
The problem than i have with this pr it's than it's a very huge breaking change also everyone is adapt to use IsAllowed to allow the open or closing instead of interacting it's probably sound good but i don't thinks most dev agree with this change

**Comment by VALERA771** [comment]
Currently IsAllowed determines can player affect door or not (open if closed and close if opened). I want to add value to block interaction. Maybe rename CanOpen to CanInteract and make it to work how IsAllowed is working? (Just like Misaka's pr)

**Comment by louis1706** [comment]
> Currently IsAllowed determines can player affect door or not (open if closed and close if opened). I want to add value to block interaction. Maybe rename CanOpen to CanInteract and make it to work how IsAllowed is working? (Just like Misaka's pr)

yeah i thinks that the best way to deal with it 

since people actually use IDeniableEvent with this one just to make unable to open/close but still getting the invalid interact sound

**Comment by Misaka-ZeroTwo** [comment]
> Currently IsAllowed determines can player affect door or not (open if closed and close if opened). I want to add value to block interaction. Maybe rename CanOpen to CanInteract and make it to work how IsAllowed is working? (Just like Misaka's pr)

My PR actually does it in a more complex way which does allow more functionality. However, given it would break a bunch of plugins, I agree with Yamato that having `CanInteract ` might be the best approach to this problem.

**Comment by VALERA771** [comment]
Closing. #160 done already

**Pull request closed without merging**
