### PR TITLE
DroppingScp330 Event Fix.

### PR DESCRIPTION
**Pull request by Undid-Iridium**
## Description
**Describe the changes** 
Candy is removed before event could be cancelled. Remove code is now called after. 

**What is the current behavior?** (You can also link to an open issue here)
Candy is removed before event could be cancelled. 

**What is the new behavior?** (if this is a feature change)
N/A

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
N/A

**Other information**:

<br />

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentations
<br />

## Submission checklist

- [X] I have checked the project can be compiled
- [?] I have tested my changes and it worked as expected

### Patches (if there are any changes related to Harmony patches)
- [X] I have checked no IL patching errors in the console

### Other
- [X] Still requires more testing

### CODE REVIEW

**Comment by ALEXWARELLC** [comment]
Related Bug Report: https://discord.com/channels/656673194693885975/1277659466463969424/1277659466463969424 (Discord)

**Comment by ALEXWARELLC** [comment]
Hello!

Please fix the build errors so I may receive a usable build from GitHub Actions?

Thanks

**Comment by Undid-Iridium** [comment]
> Hello!
> 
> Please fix the build errors so I may receive a usable build from GitHub Actions?
> 
> Thanks


image

**Comment by ALEXWARELLC** [comment]
Awesome, I'll do some testing later and will approve this PR if I don't find any issues :)

**Review by ALEXWARELLC — APPROVED** [review]
Everything appears to be in order and the event patch works as expected.

This PR can now be approved for merging.

**Comment by Undid-Iridium** [comment]
image

FYI, it would advisable to consider 

image

as this IL code just directly pulls from the array itself instead of doing any protection checks. I would be surprised if the worst case scenario occurred; however, just food for thought.

**Comment by ALEXWARELLC** [comment]
> image
> 
> 
> 
> FYI, it would advisable to consider 
> 
> 
> 
> image
> 
> 
> 
> as this IL code just directly pulls from the array itself instead of doing any protection checks. I would be surprised if the worst case scenario occurred; however, just food for thought.

If you feel like adding protection checks, go for it, but I don't think it's REALLY needed. Good food for thought :)

**Review by VALERA771 — APPROVED** [review]

**Pull request merged**
