### PR TITLE
Added ability for NPCs to be spawned in a way that they can be seen in the RA

### PR DESCRIPTION
**Pull request by TtroubleTT**
…mode

## Description
**Describe the changes**
Dummies that declare their userID as PlayerAuthenticationManager.Host will use ClientInstanceMode.Host. This will make it so those dumbies can be seen in the RA making it easier to test. 

**What is the current behavior?** (You can also link to an open issue here)
Current behavior is no matter what setup you use in NPC.Spawn() the dummies won't be seen in the RA. 

**What is the new behavior?** (if this is a feature change)
New Behavior makes it so if you set the userId to PlayerAuthenticationManage.Host then it will spawn a dummy with ClientInstanceMode.Host and you will be able to see them in the RA. 

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
Shouldn't break anything as you would have to specifically set the userID to PlayerAuthenticationManager.Host.  

**Other information**:

<br />

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentations
<br />

## Submission checklist

- [x] I have checked the project can be compiled
- [x] I have tested my changes and it worked as expected

### Patches (if there are any changes related to Harmony patches)
- [ ] I have checked no IL patching errors in the console

### Other
- [ ] Still requires more testing

### CODE REVIEW

**Comment by VALERA771** [comment]
Can you also change this in another spawn method?

**Comment by TtroubleTT** [comment]
> Can you also change this in another spawn method?

Like make another spawn method. What about just making Host be an option you put in as a string?

**Comment by Tamago4a** [comment]
You don't need to do this. Why should I see NPCs in the player list? If I need to get NPCs, I use Npc.List. We've been making it possible for NPCs to work normally on the server for a long time, and now someone wants to break everything again.

**Comment by TtroubleTT** [comment]
> You don't need to do this. Why should I see NPCs in the player list? If I need to get NPCs, I use Npc.List. We've been making it possible for NPCs to work normally on the server for a long time, and now someone wants to break everything again.

Current way it works makes it hard to test things with NPCs as they don't show up in the RA. If I make it an override wouldn't all of your stuff keep working as youd have to specify host specifically.

**Comment by TtroubleTT** [comment]
Ok iv now changed it so where it shouldn't mess with any current functionality but lets ppl choose if they want to use the mode that lets them show up in the RA.

**Comment by Tamago4a** [comment]
> Ok iv now changed it so where it shouldn't mess with any current functionality but lets ppl choose if they want to use the mode that lets them show up in the RA.

This option is more acceptable. However, I still don't fully understand how it will work in practice.

**Comment by TtroubleTT** [comment]
> > Ok iv now changed it so where it shouldn't mess with any current functionality but lets ppl choose if they want to use the mode that lets them show up in the RA.
> 
> This option is more acceptable. However, I still don't fully understand how it will work in practice.

The orginially use for NPCs wasnt like for gameplay plugins. It was for testing other plugins using them as sometimes its hard to find other people to get on and test with you. If you dont spawn them as Host they won't show up in the RA and it makes it really hard to set their class or all the other commands.

**Review by VALERA771 — APPROVED** [review]

**Review by louis1706 — APPROVED** [review]

**Review by Misfiy — APPROVED** [review]

**Pull request closed without merging**
