### PR TITLE
docs: better grammar and spelling

### PR DESCRIPTION
**Pull request by JayXTQ**
## Description
Here all I do is change some minor things like the documentation where the English used is incorrect or just has spelling mistakes.

**What is the current behavior?** (You can also link to an open issue here)
No behaviour

**What is the new behavior?** (if this is a feature change)
No behaviour

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

**Other information**:

<br />

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentations
<br />

## Submission checklist

- [x] I have checked the project can be compiled
- [ ] I have tested my changes and it worked as expected

### Patches (if there are any changes related to Harmony patches)
- [ ] I have checked no IL patching errors in the console

### Other
- [ ] Still requires more testing

### CODE REVIEW

**Review by VladTheCow — COMMENTED** [review]
I'd say the changes are useless

**Comment by JayXTQ** [comment]
Maybe, maybe not, but it's correct English and if it's not wanted then fine, I just thought I would help out. I have some more changes I want to make too but not like this, just general documentation changes where clarification is needed

**Review by Misaka-ZeroTwo — APPROVED** [review]

**Review by VALERA771 — APPROVED** [review]
This is the biggest breaking changes I've ever seen! (joke)

**Comment by VALERA771** [comment]
Can you try compiling project on release? If you have already done it then put a tick in description

**Comment by Misaka-ZeroTwo** [comment]
> Can you try compiling project on release? If you have already done it then put a tick in description

Dev CI builds in release mode

**Comment by louis1706** [comment]
> I always thought Stylecop made it whether or not.

I honestly thought the same so that weird i would have expected error.

**Comment by JayXTQ** [comment]
> Can you try compiling project on release? If you have already done it then put a tick in description

Let me try now

**Comment by JayXTQ** [comment]
Only error I get is 

```
3>Microsoft.Common.CurrentVersion.targets(5932,5): Error MSB3073 : The command "if not "C:\Users\Jay\Documents\GitHub\EXILED\EXILED\bin\Debug"=="" copy /y "C:\Users\Jay\Documents\GitHub\EXILED\EXILED\\bin\Debug\Exiled.Permissions.dll" "C:\Users\Jay\Documents\GitHub\EXILED\EXILED\bin\Debug\Plugins\"" exited with code 1.
3>------- Finished building project: Exiled.Permissions. Succeeded: False. Errors: 1. Warnings: 0
```

**Review by Jesus-QC — APPROVED** [review]
Lgtm

**Comment by Jesus-QC** [comment]
> I always thought Stylecop made it whether or not.

I think they changed it recently and decided to remove the or not part.

**Review by Mikihero — APPROVED** [review]
ultimately doesn't matter but there is no reason to not merge it imo

**Pull request merged**
