### PR TITLE
Changes for 14.0

### PR DESCRIPTION
**Pull request by Mikihero**
## Description
**Describe the changes** 
Mostly an outline of xml docs so stylecop lets me compile lol

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?** (if this is a feature change)

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

**Other information**:

<br />

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentations
<br />

## Submission checklist

- [x] I have checked the project can be compiled
- [ ] I have tested my changes and it worked as expected

### Patches (if there are any changes related to Harmony patches)
- [ ] I have checked no IL patching errors in the console

### Other
- [ ] Still requires more testing

### CODE REVIEW

**Comment by Mikihero** [comment]
I have literally never done smth like this with events so please lmk if it doesn't look right

**Comment by VALERA771** [comment]
Can you just write docs for these methods?

**Comment by Mikihero** [comment]
> Can you just write docs for these methods?

I will, I am working on #246 rn and that will need a lot of docs as well, once I'm done with that I'll work on this

**Comment by VALERA771** [comment]
Waiting for docs

**Comment by VALERA771** [comment]
You can close it then if you want

**Pull request closed without merging**
