### PR TITLE
Fix SpawnPoint

### PR DESCRIPTION
**Pull request by SrLicht**
## Description
**Describe the changes** 
Fixes RoomSpawnPoint when used in Surface and also gives a little more delay so that Lockers and etc. can be generated correctly.

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?** (if this is a feature change)

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

**Other information**:

<br />

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentations
<br />

## Submission checklist

- [ ] I have checked the project can be compiled
- [ ] I have tested my changes and it worked as expected

### Patches (if there are any changes related to Harmony patches)
- [ ] I have checked no IL patching errors in the console

### Other
- [ ] Still requires more testing

### CODE REVIEW

**Comment by Josephfallen** [comment]
what in the holy PR is this

**Comment by SrLicht** [comment]
> what in the holy PR is this

idk github, the onlychange is this

imagen

**Comment by SrLicht** [comment]
Hmm maybe my branch is bugged or i made the forkupdate wrong XD

**Comment by Josephfallen** [comment]
@SrLicht You've done some goofy stuff

**Comment by SrLicht** [comment]
> @SrLicht You've done some goofy stuff

Yes, the worst of all is that I don't know how to fix it... heeelp

**Comment by Josephfallen** [comment]
@SrLicht Just re make it in VS and test it

**Pull request closed without merging**
