### PR TITLE
feat: Add and remove influence

### PR DESCRIPTION
**Pull request by Bonjemus**
## Description
**Describe the changes** 
It seemed pretty weird to me that those functions weren't here in the first place.

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?** (if this is a feature change)

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No.

**Other information**:

<br />

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentations
<br />

## Submission checklist

- [ ] I have checked the project can be compiled
- [ ] I have tested my changes and it worked as expected

### Patches (if there are any changes related to Harmony patches)
- [ ] I have checked no IL patching errors in the console

### Other
- [ ] Still requires more testing

### CODE REVIEW

**Comment by YongAn404** [comment]
You can add these two together as well
```cs
 public static float GetInfluence(Faction faction)
 {
     return FactionInfluenceManager.Get(faction);
 }
 public static void SetInfluence(Faction faction, float influence)
 {
     FactionInfluenceManager.Set(faction, influence);
 }
```

**Comment by Bonjemus** [comment]
Done. 👍

**Review by VALERA771 — COMMENTED** [review]
Everytring can be inlined

**Review by Misfiy — CHANGES_REQUESTED** [review]
like asked by valera: use inlining

**Comment by Bonjemus** [comment]
> like asked by valera: use inlining

Y e s

**Comment by VALERA771** [comment]
Everyting is good but PR must target dev branch

**Review by Misfiy — APPROVED** [review]

**Pull request merged**
