### PR TITLE
Interacting scp330 compile fix

### PR DESCRIPTION
**Pull request by Undid-Iridium**
## Description
**Describe the changes** 
Skill issue (Or rather my scp server does not compile with error, for whatever reason).

**What is the current behavior?** (You can also link to an open issue here)
Compile bug

**What is the new behavior?** (if this is a feature change)
Interact event compiles correctly (I am going to assume Yamato double checked but someone else should too).

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

**Other information**:
Yamato and I went back and forth on why my scp instance did not throw a compile error for this, but did for his pr that resolves a bug, no idea why. The only difference is windows versions, and system's themselves. Even built on his branch + changes I did not get a compile error or warning. Very weird (and yes I tried both debug and release build).

<br />

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentations
<br />

## Submission checklist

- [X] I have checked the project can be compiled (Someone double check, my system for whatever reason even on a clean build did not complain, I have zero idea why)
- [] I have tested my changes and it worked as expected (See above).

### Patches (if there are any changes related to Harmony patches)
- [] I have checked no IL patching errors in the console (see above)
 
### Other
- [] Still requires more testing (see above)

### CODE REVIEW

**Comment by ITeMbI4** [comment]
```
HarmonyLib.HarmonyException: Patching exception in method virtual System.Void Interactables.Interobjects.Scp330Interobject::ServerInteract(ReferenceHub ply, System.Byte colliderId) ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: opcode
```

**Comment by Undid-Iridium** [comment]
> ```
> HarmonyLib.HarmonyException: Patching exception in method virtual System.Void Interactables.Interobjects.Scp330Interobject::ServerInteract(ReferenceHub ply, System.Byte colliderId) ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: opcode
> ```

Alright well I don't get any compile error's - again.. sigh

**Comment by Undid-Iridium** [comment]
Sigh - EventPatch is suppressing my error.

**Comment by Undid-Iridium** [comment]
Would you look at that, I can fix things when I get errors

**Comment by Undid-Iridium** [comment]
image
Sigh

**Comment by Undid-Iridium** [comment]
Tested it again, seems to work, someone else verify as well. Now I need to remember to check harmony logs in case error gets eaten up

**Review by Misfiy — APPROVED** [review]

**Comment by ITeMbI4** [comment]
@Undid-Iridium seems like works fine

**Comment by Undid-Iridium** [comment]
> @Undid-Iridium seems like works fine

🙏

**Review by louis1706 — APPROVED** [review]

**Pull request merged**
