### PR TITLE
[Exiled.API] add gameobject and trasform to lockers

### PR DESCRIPTION
**Pull request by adarkaz**
## Description
**Describe the changes** 
add gameobject and trasform to lockers

**What is the current behavior?** (You can also link to an open issue here)
no😥😫😫😫❎❌❌❌❗❗

**What is the new behavior?** (if this is a feature change)
yes✅✅✅✅✅

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

**Other information**:

<br />

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentations
<br />

## Submission checklist

- [x] I have checked the project can be compiled
- [x] I have tested my changes and it worked as expected

### Patches (if there are any changes related to Harmony patches)
- [x] I have checked no IL patching errors in the console

### Other
- [x] Still requires more testing

### CODE REVIEW

**Comment by IRacle1** [comment]
🤯🤯🤯🤯🤯🤯😰😰😰😰🔥🔥🔥🔥🔥🔥

**Review by IRacle1 — APPROVED** [review]
🔥🔥🔥😉😉😉😉😉😊😊🐟🐟🤯🤯✅✅📈📈😈😈🐹🐹🤩🤩😍😍

**Comment by IRacle1** [comment]
bro😭😭

**Review by louis1706 — APPROVED** [review]
✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅🏳️‍⚧️🏳️‍⚧️

**Comment by Marikider** [comment]
our elephant

**Review by Misfiy — APPROVED** [review]

**Pull request merged**
